spring:
  application:
    name: effective_mobile

  datasource:
    url: jdbc:postgresql://localhost:5433/tw2
    username: student
    password: chocolatefrog
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      create-drop
#      update
    show-sql: true

  spring:
    cors:
      url:
        configurations:
          - "[/**]":
              allowed-origins:
                - "*"
              allowed-methods:
                - GET, POST, PUT, DELETE, OPTIONS
              allowed-headers:
                - "*"
              allow-credentials: false
              max-age: 3600
